version: "3.9"

services:
  research-gpt-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: research-gpt-api
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      # Persist uploaded PDFs
      - ./data/papers:/app/data/papers

      # Persist vector database (very important)
      - ./data/vector_store:/app/data/vector_store

    restart: unless-stopped
